name: neon
description: Hour Blocks for Android

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.2.0+3

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


#^ Allows for automatic updating if the latest version will not break the current code
  shared_preferences: ^0.5.2
#  https://pusher:   com/tutorials/local-data-flutter:

  url_launcher: ^5.0.3

  flutter_local_notifications:
# https://pub:dev/packages/flutter_local_notifications#-installing-tab-:

  device_calendar: ^0.1.1
#  https://itnext:io/using-device-calendar-library-in-flutter-to-communicate-with-android-ios-calendar-95b2d8c77b40:

  cupertino_icons: ^0.1.2
  # Use with the CupertinoIcons class for iOS style icons.

  preferences: ^4.0.0
#  https://pub:dev/packages/preferences#-installing-tab-:

  dynamic_theme: ^1.0.1
#  https://pub: dev/packages/dynamic_theme#-installing-tab-:

  intl: ^0.15.8

  # The following section is specific to Flutter.


dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - resources/androidAdd@3x.png
    - resources/icons/bank@3x.png
    - resources/icons/brush@3x.png
    - resources/icons/calendar@3x.png
    - resources/icons/code@3x.png
    - resources/icons/commute@3x.png
    - resources/icons/couch@3x.png
    - resources/icons/default@3x.png
    - resources/icons/education@3x.png
    - resources/icons/food@3x.png
    - resources/icons/game@3x.png
    - resources/icons/gym@3x.png
    - resources/icons/health@3x.png
    - resources/icons/home@3x.png
    - resources/icons/love@3x.png
    - resources/icons/movie@3x.png
    - resources/icons/music@3x.png
    - resources/icons/pencil@3x.png
    - resources/icons/people@3x.png
    - resources/icons/sleep@3x.png
    - resources/icons/store@3x.png
    - resources/icons/sun@3x.png
    - resources/icons/work@3x.png
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: GoogleSans
     fonts:
       - asset: fonts/GoogleSans-Regular.ttf
       - asset: fonts/GoogleSans-Medium.ttf
         weight: 600
       - asset: fonts/GoogleSans-Bold.ttf
         weight: 800
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
